Repository Cardinal-Cryptography/aleph-node, pull requests merged in 2022-08, with the labels that each got.

#565 debugging featurenet(s)
  .github/workflows/deploy-feature-envs.yaml
  bin/node/src/chain_spec.rs
  fork-off/Cargo.lock
  fork-off/Cargo.toml
  fork-off/src/chainspec_combining.rs
  fork-off/src/types.rs
Labels: DESTROYED

#577 [A0-1114] Change deployment to devnet to be manual.
  .github/workflows/deploy-to-devnet.yml
Labels: [AZERO] DEPLOY-FEATURE-ENV

#520 A0-1088: Clean up aleph node cli
  bin/node/src/chain_spec.rs
  bin/node/src/cli.rs
  bin/node/src/commands.rs
  local-tests/chainrunner/chain.py
  local-tests/chainrunner/node.py
  scripts/run_nodes.sh
Labels: [AZERO] DEPLOY-FEATURE-ENV, DESTROYED
